development:
  adapter: postgresql
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: postgresql
  url: <%= ENV.fetch("POSTGRESQL") { "postgresql://localhost:6379/1" } %>
  channel_prefix: payme_production
